services:
  api:
    container_name: api
    image: node:24.2.0-alpine3.22
    ports:
      - ${API_GATEWAY_PORT:-3000}:3000
    volumes:
      - ./api:/api
    working_dir: /api
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=${POSTGRES_DB:-mobapp}
      - DATABASE_URL=postgresql://postgres:changeme@postgres:5432/mobapp?schema=public
    networks:
      - mobapp
    restart: "no"
    command:
      - /bin/sh
      - -c
      - |
        echo $DATABASE_URL >> .env
        corepack enable
        pnpm run start:dev

  postgres:
    image: postgres:16.8-alpine3.21
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=${POSTGRES_DB:-mobapp}
      - LC_COLLATE=fr_FR.utf8
      - LC_CTYPE=fr_FR.utf8
      - LANG=fr_FR.utf8
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - mobapp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U ${POSTGRES_USER:-postgres} -h localhost -p 5432"]
      interval: ${POSTGRES_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${POSTGRES_HEALTHCHECK_TIMEOUT:-30s}
      retries: ${POSTGRES_HEALTHCHECK_RETRIES:-3}
      start_period: ${POSTGRES_HEALTHCHECK_START_PERIOD:-0s}

networks:
  mobapp:
    driver: bridge

volumes:
  pg-data:
